# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801e4978752114908d278ef7cfa38741dbc3af660d39517eb7634588f738a84f516d609b30740e110dc0365f52125ebf95d375e019f7f4df1d2cd36c16801e97

test:
  secret_key_base: aa45ac203f4c3ef48deac0a253454713e07c390e0553c6fc12ba0d1c33bc6ce9dde5b3b8cbe8fc369cc6321859a7efd7b85a31f7260d0fbf02283ab72780c007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
